# .github/workflows/main.yml
name: network-scanner

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master & develop branches
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
    name: PHP ${{ matrix.php }}
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: validate composer.json
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          command: validate

      - name: install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: run tests
        uses: php-actions/phpunit@v3
        with:
          version: 4.8    # from composer.json
          php_version: ${{ matrix.php }}
          args: --coverage-text

  notification:
    runs-on: ubuntu-latest
    needs:  # make sure the notification is sent AFTER the jobs you want included have completed
      - unit-tests
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    timeout-minutes: 60
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
